# -*- coding: utf-8 -*-
"""Добро пожаловать в Colab!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# ***"DataFrameda" elementlarni tashlab yuborish***
"""

import pandas as pd

uz={2020:33.5,2019:32.9,2018:32.5,2017:32.9,2016:31.6,2015:30.9}
kz={2020:5.8,2019:6.5,2018:5.5,2017:6.6,2016:3.6,2015:3.5}
tj={2020:32.8,2019:85.5,2018:96.5,2017:74.6,2016:23.6,2015:33.5}
kg={2020:1.8,2019:3.5,2018:2.5,2017:4.6,2016:3.6,2015:8.5}
tr={2020:25.8,2019:98.5,2018:78.5,2017:21.6,2016:14.6,2015:56.5}

df=pd.DataFrame(
    {
        "Uzbekiston":uz,
        "Kazakiston":kz,
        "Tajikiston":tj,
        "Kirgiziston":kg,
        "Turkmaniston":tr
    }
)

print(df)

df["Uzbekiston"] # Faqat Uzbekiston ustunini chiqarish

df.loc[2019] #Faqat 1-satrni chiqarish

df1=df[["Kazakiston"]] # DataFrame turida chiqadi
type(df1)

df2=df["Kazakiston"] # Series korinishida ekranga chiqadi
type(df2)

# DataFrame ni NamPy ga otkazish
df_NumPy=df[["Uzbekiston"]].to_numpy()
print(df_NumPy)
type(df_NumPy)

# 2 dan 5 gacha bolgan satrlarni chiqarish
df[2:5]

# Shart operatori yordamida filtirlab tekshirib chiqarish
df>7

df[["Uzbekiston"]][df["Uzbekiston"]>32]

# Ustunlar bilan satrlarni almashtirish
df3=df.transpose(copy=True)
df3





